### ISSUE TITLE
Docs: Document which attributes are used for what

### ISSUE THREAD

**Issue by LordMike** [Genbox/EnumSourceGen#1]
* [x] I hereby verify that I am a sponsor.

Sponsorship is required before you can submit feature requests. See https://github.com/sponsors/Genbox

**Describe the feature**
Please document which attributes are used. I know I can use `DisplayAttribute`, and that using this will get me extensions and so on to go to/from display names. But what other attributes are used?

`DisplayAttribute` is also used in ASP.Net MVC to tweak rendering, so abusing that to store some short names is not feasible. But I don't know what I can use instead.

**Comment by Simonl9l** [comment]
If I try and use [DispayAttribute ](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.displayattribute?view=net-7.0)I get the following error:

`Attribute 'System.ComponentModel.DisplayNameAttribute' is not valid on this declaration type. It is valid on 'Class, Method, Property, Event' declarations only.`

Seems one can add the [DescriptionAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.descriptionattribute?view=net-7.0) on Enums, but this does not seem to generate anything.

**Comment by Genbox** [comment]
@Simonl9l Your error indicates you are using DisplayNameAttribute, not DisplayAttribute.
