### ISSUE TITLE
Feature: Ability to specify visibility of generated code

### ISSUE THREAD

**Issue by LordMike** [Genbox/EnumSourceGen#2]
* [x] I hereby verify that I am a sponsor.

Sponsorship is required before you can submit feature requests. See https://github.com/sponsors/Genbox

**Describe the feature**
I have a situation where I'd like to generate an internal enums helper, for a public enum. The use case is that my internal code (including internalsvisibleto code) should be able to use the helper, while the public API as exposed to others (consumers, whatnot) shouldn't. Mostly because I don't want to commit to maintaining this helper.

Examples like the below snippet would be awesome to have configurable:
* https://github.com/Genbox/EnumSourceGen/blob/4777105245b3df063020f4507becca6cbe02b0a4/Src/EnumSourceGen/Generators/EnumClassCode.cs#L20

**Comment by Genbox** [comment]
Releaed in 1.0.0-alpha.14
Note that the package changed named to FastEnum

**Comment by Genbox** [comment]
See https://github.com/Genbox/FastEnum/blob/master/Src/FastEnum.Tests.CodeGen/Resources/VisibilityOverride.input for usage
